config/routes.rb
Rails.application.routes.draw do

  root 'runs#index'

  resources :runs do
    get :rules
    get :test
  end
end

app/models/run.rb
class Run < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show]
  before_action :set_run_by_run_id, only: [:rules, :test]

  # GET /runs
  def new
    @run = Run.new
  end

  # GET /runs
  def index
    @runs = Run.all.order('id DESC') #.paginate(page: params[:page], per_page: 10)
  end

  # GET /runs/1
  def show
    @reduct_set = @run.reduct_set.split.each
  end

  # POST /runs
  def create
    @run = ::Run.new(run_params)

    if @run.rules.rindex('},') == @run.rules.rindex('}')
      @run.rules[@run.rules.rindex('},')...(@run.rules.rindex('},') + '},'.length)] = "}"
    end

    if @run.save
      redirect_to @run, notice: 'Run was successfully created.'
    else
      render :new
    end
  end

  # GET /runs/1/rules
  def rules
    @rules_hash = JSON.parse @run.rules
    @reduct_set = @run.reduct_set.split.each
  end

  # GET /runs/1/test
  def test
    @rules_hash = JSON.parse @run.rules
    @reduct_set = @run.reduct_set.split.each
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      begin
        @run = Run.find(params[:id])
      rescue Exception => e
        redirect_to action: 'index', notice: 'This run doesn\'t exist.'
        return
      end
    end

    def set_run_by_run_id
      begin
        @run = Run.find(params[:run_id])
      rescue Exception => e
        redirect_to action: 'index', notice: 'This run doesn\'t exist.'
        return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:name, :reduct_set, :rules)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feature Selection</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Feature Selection</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <li<%= raw ' class="active"' if controller_name == "runs" %>>
            <a href="<%= runs_path %>">Runs <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>

  <div class="form-group">
    <%= f.label :reduct_set %><br>
    <%= f.text_field :reduct_set, class: 'form-control' %>
  </div>
  <br>

  <div class="form-group">
    <%= f.label :rules %><br>
    <%= f.text_area :rules, class: 'form-control', rows: 6 %>
  </div>
  <br>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/runs/index.html.erb
<h1>List of Runs</h1>
<hr>

<% if params[:notice] != nil %>
<div class="alert alert-danger" role="alert"><%= params[:notice] %></div>
<% end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Submitted</th>
      <th colspan="3" width="40%">Controls</th>
    </tr>
  </thead>

  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= run.id %></td>
        <td><%= run.name %></td>
        <td><%= run.created_at.strftime('%b %e, %l:%M:%S %p') %></td>
        <td>
          <%= link_to run do %>
          <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> View Run
          <% end %>
        </td>
        <td>
          <%= link_to run_rules_path(run) do %>
          <span class="glyphicon glyphicon-list" aria-hidden="true"></span> List Rules
          <% end %>
        </td>
        <td>
          <%= link_to run_test_path(run) do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Test Sample
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%#= will_paginate @problems, renderer: BootstrapPagination::Rails %>
<br>
<br>

app/views/runs/new.html.erb
<h1>New Run</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Back to list of Runs', runs_path, class: 'btn btn-default' %>

app/views/runs/rules.html.erb
<h1>Viewing Rules</h1>
<hr>

<% if notice %>
<div class="alert alert-success"><%= notice %></div>
<% end %>

<p>
  <strong>Run Name:</strong>
  <%= @run.name %>
</p>

<p>
  <strong>Rules Generated:</strong>
</p>

<table class="table table-bordered table-striped table-hover centered">
  <thead>
    <% @reduct_set.each do |serial| %>
      <th>Attribute #<%= serial %></th>
    <% end %>
    <th>Decision value</th>
  </thead>

  <tbody>
    <% @rules_hash.each do |rule| %>
    <tr>
      <% @reduct_set.each do |serial| %>
        <td>
          <% if rule['values'][serial] != nil %>
            <%= rule['values'][serial] %>
          <% else %>
            <div class="dont_care">Don't care</div>
          <% end %>
        </td>
      <% end %>
      <td><%= rule['decision_value'] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to list of Runs', runs_path, class: 'btn btn-default' %>

app/views/runs/show.html.erb
<h1>Viewing Run</h1>
<hr>

<% if notice %>
<div class="alert alert-success"><%= notice %></div>
<% end %>

<p>
  <strong>Run Name:</strong>
  <%= @run.name %>
</p>

<p>
  <strong>Reduct Set:</strong>
</p>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <th>Attribute #</th>
    <th>Attribute Name</th>
  </thead>

  <tbody>
    <% @reduct_set.each do |serial| %>
    <tr>
      <td><%= serial %></td>
      <td>Unknown</td>
    </tr>
    <% end %>
  </tbody>
</table>

<p>
  <strong>Rules generated:</strong>
  <%= link_to 'Click here to view the rules', run_rules_path(@run) %>
</p>

<% if false %>
<!--
<p>
  <strong>Tested:</strong>
  <% if @run.tested %>&check;<% else %>&#10007;<% end %>
</p>

<p>
  <strong>Success:</strong>
  <% if @run.success %>&check;<% else %>&#10007;<% end %>
</p>

<p>
  <strong>Submitted:</strong>
  <%= @run.timestamp.strftime('%b %e, %l:%M:%S %p') %>
</p>

<hr>

<p>
  <strong>Statement:</strong>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= raw @run.problem.statement %>
    </div>
  </div>
</p>

<p>
  <strong>Sample input:</strong>
  <pre><%= @run.problem.sample_input %></pre>
</p>

<p>
  <strong>Sample output:</strong>
  <pre><%= @run.problem.sample_output %></pre>
</p>

<hr>

<p>
  <strong>Source code:</strong>
  <pre class="prettyprint"><%= @run.code %></pre>
</p>

<% if @run.tested and not (@run.comments.nil? or @run.comments.empty?) %>

<br>
<p>
  <strong>Moderator's comments:</strong>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= raw @run.comments %>
    </div>
  </div>
</p>

<% end %>
-->
<% end %>


<br>

<%= link_to 'Back to list of Runs', runs_path, class: 'btn btn-default' %>

app/views/runs/test.html.erb
<h1>Viewing Run</h1>
<hr>

<% if notice %>
<div class="alert alert-success"><%= notice %></div>
<% end %>

<p>
  <strong>Run Name:</strong>
  <%= @run.name %>
</p>

<br>

<p>
  <strong>Test Sample:</strong>
</p>

<textarea class="form-control" rows="10"></textarea><br><br>

<p>
  <strong>Diagnosed Decision Value:</strong>
</p>

<input type="text" class="form-control" readonly></input>

<br>

<button class="btn btn-success" onclick="predict()">Predict Decision Value</button><br><br>

<br>

<script type="text/javascript">
  tree = <%= raw @run.rules %>;

  predict = function() {
    attributes = $('textarea').val().split(" ");
    match_found = false;

    for(j = 0; j < tree.length && match_found === false; j++)
    {
      node = tree[j];

      $match = true;
      $keys = Object.keys(node.values);

      for(i = 0; i < $keys.length; i++)
      {
        if(node.values[$keys[i]] != attributes[$keys[i]])
          $match = false;
      }

      if($match) {
        $('input').val(node.decision_value);
        match_found = true;
      }

    }

    if(!match_found) {
      $('input').val("No match found");
    }
  }
</script>

<%= link_to 'Back to list of Runs', runs_path, class: 'btn btn-default' %>